common/models/Pitanje.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "pitanje".
 *
 * @property int $id
 * @property string|null $pitanje
 * @property string|null $opis
 * @property int|null $upitnik
 * @property bool|null $is_required
 * @property int|null $vrsta_pitanja
 * @property string|null $odgovori
 *
 * @property Odgovori[] $odgovoris
 * @property Upitnik $upitnik0
 * @property VrstaPitanja $vrstaPitanja
 */
class Pitanje extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pitanje';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['opis'], 'string'],
            [['upitnik', 'vrsta_pitanja'], 'default', 'value' => null],
            [['upitnik', 'vrsta_pitanja'], 'integer'],
            [['is_required'], 'boolean'],
            [['odgovori'], 'safe'],
            [['pitanje'], 'string', 'max' => 250],
            [['upitnik'], 'exist', 'skipOnError' => true, 'targetClass' => Upitnik::className(), 'targetAttribute' => ['upitnik' => 'id']],
            [['vrsta_pitanja'], 'exist', 'skipOnError' => true, 'targetClass' => VrstaPitanja::className(), 'targetAttribute' => ['vrsta_pitanja' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'pitanje' => Yii::t('app', 'Pitanje'),
            'opis' => Yii::t('app', 'Opis'),
            'upitnik' => Yii::t('app', 'Upitnik'),
            'is_required' => Yii::t('app', 'Is Required'),
            'vrsta_pitanja' => Yii::t('app', 'Vrsta Pitanja'),
            'odgovori' => Yii::t('app', 'Odgovori'),
        ];
    }

    /**
     * Gets query for [[Odgovoris]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOdgovoris()
    {
        return $this->hasMany(Odgovori::className(), ['pitanje' => 'id']);
    }

    /**
     * Gets query for [[Upitnik0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUpitnik0()
    {
        return $this->hasOne(Upitnik::className(), ['id' => 'upitnik']);
    }

    /**
     * Gets query for [[VrstaPitanja]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVrstaPitanja()
    {
        return $this->hasOne(VrstaPitanja::className(), ['id' => 'vrsta_pitanja']);
    }
}

backend/controllers/PitanjeController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Pitanje;
use common\models\Search\PitanjeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PitanjeController implements the CRUD actions for Pitanje model.
 */
class PitanjeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pitanje models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PitanjeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pitanje model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pitanje model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pitanje();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pitanje model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pitanje model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pitanje model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pitanje the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pitanje::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/PitanjeController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Pitanje;
use common\models\Search\PitanjeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PitanjeController implements the CRUD actions for Pitanje model.
 */
class PitanjeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pitanje models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PitanjeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pitanje model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pitanje model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pitanje();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pitanje model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pitanje model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pitanje model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pitanje the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pitanje::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/pitanje/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model common\models\Pitanje */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pitanje-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'pitanje')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'opis')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'upitnik')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(
            \common\models\Upitnik::find()->all(),
            'id',
            'naziv'
        ),
    ]) ?>

    <?= $form->field($model, 'is_required', ['template' => '{input}{label}{error}'])->checkbox(['label' => 'obavezno']) ?>

    <?= $form->field($model, 'vrsta_pitanja')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(
            \common\models\VrstaPitanja::find()->all(),
            'id',
            'vrsta_pitanje'

        ),
    ]) ?>

    <?= $form->field($model, 'odgovori')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pitanje/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Search\PitanjeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pitanje-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'pitanje') ?>

    <?= $form->field($model, 'opis') ?>

    <?= $form->field($model, 'upitnik') ?>

    <?= $form->field($model, 'is_required')->checkbox() ?>

    <?php // echo $form->field($model, 'vrsta_pitanja') ?>

    <?php // echo $form->field($model, 'odgovori') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pitanje/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Pitanje */

$this->title = Yii::t('app', 'Create Pitanje');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pitanjes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pitanje-create">
    <div class="card">
        <div class="card-header card-header-primary">
            <span class="card-title"><?= Html::encode($this->title) ?></span>
        </div>
        <div class="card-body">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>

        </div>
    </div>
</div>

backend/views/pitanje/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\Search\PitanjeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Pitanja');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pitanje-index">

    <div class="card">
        <div class="card-header card-header-primary">
            <span class="card-title"><?= Html::encode($this->title) ?></span>
            <?= Html::a('<span class="material-icons">add</span>', ['create'], ['class' => 'btn btn-success']) ?>
        </div>
        <div class="card-body">

            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    // ['class' => 'yii\grid\SerialColumn'],

                    'id',
                    'pitanje',
                    'opis:ntext',
                    'upitnik0.naziv',
                    'is_required:boolean',

                    //'vrsta_pitanja',
                    //'odgovori',


                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view}{update}',
                        // 'visible' => Yii::$app->user->can('admin'),
                        'buttons' => [
                            'view' => function ($url, $data) {

                                $url2 = \Yii::$app->urlManager->createUrl(['pitanje/view', 'id' => $data->id]);
                                return Html::a('<span class="material-icons">visibility</span>', $url2, [
                                    'title' => Yii::t('app', 'Pogledaj'),
                                ]);
                            },

                            'update' => function ($url, $data) {
                                $url2 = \Yii::$app->urlManager->createUrl(['pitanje/update', 'id' => $data->id]);
                                return Html::a('<span class="material-icons">create</span>', $url2, [
                                    'title' => Yii::t('app', 'Ažuriraj'),
                                ]);
                            },


                        ],
                    ],
                ],
            ]); ?>


        </div>
    </div>
</div>

backend/views/pitanje/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Pitanje */

$this->title = Yii::t('app', 'Update Pitanje: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pitanjes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="pitanje-update">
    <div class="card">
        <div class="card-header card-header-primary">
            <span class="card-title"><?= Html::encode($this->title) ?></span>
        </div>
        <div class="card-body">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>

        </div>
    </div>
</div>

backend/views/pitanje/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Pitanje */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pitanjes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="pitanje-view">
    <div class="card">
        <div class="card-header card-header-primary">
            <span class="card-title"><?= Html::encode($this->title) ?></span>


            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>

        </div>
        <div class="card-body">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'pitanje',
                    'opis:ntext',
                    'upitnik',
                    'is_required:boolean',
                    'vrsta_pitanja',
                    'odgovori',
                ],
            ]) ?>

        </div>
    </div>
</div>